name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Build Next.js app
        run: npm run build --prefix frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        uses: actions/deploy@v1
        with:
          provider: 'ssh'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd backend
            gunicorn app:app --bind 0.0.0.0:8000
